/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primeroadsi209;

/**
 *
 * @author SENA
 */
public class notas extends javax.swing.JFrame {
    int numeros[]=new int[10];
    int cont=0;

    /**
     * Creates new form notas
     */
    public notas() {
        initComponents();
        contador.setText("cantidad de datos: "+cont);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdato = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        lbtotal = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatoActionPerformed(evt);
            }
        });
        jPanel1.add(txtdato, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 51, 230, 44));

        btn1.setText("guardar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 113, 117, -1));

        lbtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbtotal.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 187, 179, 88));

        contador.setText("jLabel1");
        jPanel1.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 23, 267, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        ejecutar();
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtdatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JLabel contador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField txtdato;
    // End of variables declaration//GEN-END:variables

    
    // 0=1  1=2  2=3  3=4
    private void ejecutar() {
      
        System.out.println(""+cont);
        if (cont==9) {
            btn1.setText("calcular");
        }
        if (cont==10) {
            
            int acumulador=0;
            for (int i = 0; i < numeros.length; i++) {
               acumulador+=numeros[i]; 
            }
            
            int total=acumulador/10;
            
            lbtotal.setText("su promedio es: "+total);
            cont=0;
            
            
            
        }else{
            numeros[cont]=Integer.parseInt(txtdato.getText());
        }
        
        txtdato.setText("");
        txtdato.requestFocus();
        
          cont++;
          
          contador.setText("cantidad de datos: "+cont);
    }
}
